### ISSUE TITLE
from opus install decoder

### ISSUE THREAD

**Issue by el07694** [svartalf/python-opus#4]
I downloaded the git repository and then i run:
```
python setup.py build
python setup.py install

```
after that i have this error:

```
>>> import opus.decoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Χρήστος\AppData\Local\Programs\Python\Python38\lib\site-packages\opus-0.0.1-py3.8.egg\opus\decoder.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Χρήστος\AppData\Local\Programs\Python\Python38\lib\site-packages\opus-0.0.1-py3.8.egg\opus\api\__init__.py", line 5, in <module>
  File "C:\Users\Χρήστος\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

Any advice?

**Comment by svartalf** [comment]
This project is not maintained, you can use any of forks available, such as https://github.com/orion-labs/opuslib
